workflows:
  android-build:
    name: Build Aljorany APK
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: "production"
      node: stable
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Fix Capacitor permission
        script: |
          chmod +x node_modules/.bin/cap
      - name: Copy Capacitor assets
        script: |
          npx cap copy
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk